services:
  app:
    image: ghcr.io/your-org/demo-app:latest
    env_file:
      - .env
    ports:
      - "${SERVER_PORT:-8080}:8080"
    networks:
      - external-net
    depends_on:
      - db

  db:
    image: mariadb:11
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - external-net

volumes:
  mariadb_data:

networks:
  external-net:
    external: true
    name: sample-network
