server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:demo_db}
    username: ${DB_USERNAME:demo_user}
    password: ${DB_PASSWORD:demo_password}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}  # ?? ? validate ?? none ??
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:true}
        dialect: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    root: ${LOG_ROOT_LEVEL:info}
    org.springframework.web: ${LOG_WEB_LEVEL:debug}
    com.demo: ${LOG_APP_LEVEL:debug}  # ???? ??? ??