# 워크플로우 이름 설정 - GitHub Actions 대시보드에 표시됨
name: DEV CI - Build & Test

# 워크플로우가 실행될 트리거 조건 설정
on:
  # dev 브랜치로 Pull Request 생성 또는 업데이트 시 실행
  pull_request:
    branches: [ dev ]

  # dev 브랜치로 직접 Push될 때도 실행
  push:
    branches: [ dev ]

jobs:
  build:
    # 실행할 머신 환경 - 최신 Ubuntu LTS 버전 사용
    runs-on: ubuntu-latest

    steps:
      # 1단계: 소스 코드를 runner에 체크아웃
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2단계: JDK 17 설치 및 설정 (Temurin 배포판 사용)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'     # 사용할 JDK 배포판 (Temurin: OpenJDK 중 하나)
          java-version: '17'          # 설치할 JDK 버전

      # 3단계: Gradle Wrapper 파일에 실행 권한 부여 (Linux 환경에서 필수)
      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      # 4단계: Gradle로 빌드 및 테스트 실행
      - name: Build & run tests
        run: ./gradlew clean build --no-daemon -x test
        # clean build: 빌드 이전 결과물 삭제 후 새로 빌드
        # --no-daemon: CI 환경에서는 데몬 비활성화 권장
        # -x test: 테스트는 제외하고 빌드만 수행
