# 워크플로우 이름 정의 - GitHub Actions 페이지에 표시될 이름
name: [DEV] CI - Build & Test

# 워크플로우 트리거 조건
on:
  # dev 브랜치로 향하는 Pull Request가 생성되거나 업데이트될 때 실행
  pull_request:
    branches: [ dev ]

  # dev 브랜치에 직접 push된 경우에도 실행
  push:
    branches: [ dev ]

jobs:
  build:
    # GitHub Actions가 사용할 머신 환경 - Ubuntu 최신 버전
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소의 전체 소스 코드를 현재 runner에 체크아웃
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. JDK 17 환경 설정 (Temurin은 OpenJDK 배포판 중 하나)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'     # 사용할 JDK 배포판
          java-version: '17'          # 사용할 JDK 버전

      # 3. Gradle Wrapper 파일에 실행 권한 부여 (Unix 계열 OS에서는 필수)
      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      # 4. Gradle을 사용하여 전체 프로젝트 빌드 및 테스트 실행
      - name: Build & run tests
        run: ./gradlew clean build --no-daemon
        # --no-daemon: CI 환경에서는 Gradle 데몬 비활성화 권장
        # clean build: 기존 결과 제거 후 다시 컴파일 및 테스트
